name: build doc

on:
  push:

jobs:
  doc:
    name: build doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python3 -m pip install .\[dev\]

      - name: Test
        run: |
          python3 -m pytest

      - name: doc
        run: |
          cd docs
          make html
          mv _build/html ../docs
          cd ..
